// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations"
  },
  // Use DIRECT_URL for migrations (bypasses Supabase PgBouncer pooler)
  // Falls back to DATABASE_URL if DIRECT_URL is not set
  datasource: {
    url: (process.env.DIRECT_URL ?? process.env.DATABASE_URL) as string
  }
});
